name: Java CI with Gradle

on:
  push:
    branches: [ "**" ] # Запускать на пуш в любую ветку
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: # Добавляет кнопку ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Обновил до v4 (актуальная версия)
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4 # Обновил до v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Обновил до v4
        with:
          name: SecretRoomsMod
          path: build/libs
